hospital_proj/hos_app/urls.py
from django.urls import path
from . import views
app_name='hos' 
urlpatterns = [
    path('',views.Home,name='home'),
    path('about/',views.about,name='about'),
    path('test/',views.test,name='test'),
    path('package/',views.package,name='package'),
    path('blog/',views.blog,name='blog'),
    path('gallery/',views.gallery,name='gallery'),
    path('branches/',views.branches,name='branches'),
    path('contacts/',views.contacts,name='contacts'),
    path('branchplace/<int:id>',views.branchplace,name='branchplace'),
    path('blogpage/',views.blogpage,name='blogpage'),
    path('blogpage1/',views.blogpage1,name='blogpage1'),
    path('packages/<int:id>',views.packages,name='packages'),
    path('appointment/',views.appointment,name='appointment'),
    path('privacy/',views.privacy,name='privacy'),
    path('term/',views.term,name='term'),
    path('depart/',views.depart,name='depart'),
 

]

hospital_proj/hospital_proj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('hos_app.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

hospital_proj/hos_app/models.py
from django.db import models

# Create your models here.

class Homes(models.Model):
    name=models.CharField(max_length=250)
    image=models.ImageField(upload_to='homes',null=True,blank=True)

    class Meta:
        ordering=('name',)
        
        
    def __str__(self):
        return self.name




class Testimo(models.Model):
    name=models.CharField(max_length=50)
    detail=models.CharField(max_length=250)
    place=models.CharField(max_length=100)

        
    def __str__(self):
        return self.name





class Enquery(models.Model):
    names=models.CharField(max_length=250)
    email=models.CharField(max_length=250)
    number=models.IntegerField(unique=True)
    message=models.CharField(max_length=300)
  
        
    def __str__(self):
        return self.names


class Appointment(models.Model):
    name=models.CharField(max_length=200)
    email=models.CharField(max_length=100)
    phone=models.IntegerField(unique=True)
    date=models.CharField(max_length=10)
    time=models.CharField(max_length=10)
    age=models.IntegerField()
    gender=models.CharField(max_length=50)
    address=models.CharField(max_length=250)
    message=models.CharField(max_length=250)

    def __str__(self):
        return self.name




class Contact(models.Model):
    name=models.CharField(max_length=200)
    email=models.CharField(max_length=100)
    phone=models.IntegerField(unique=True)
    subject=models.CharField(max_length=200)
    message=models.CharField(max_length=250)
    
    def __str__(self):
        return self.name



class Branch(models.Model):
    image=models.ImageField(upload_to='branch')
    name=models.CharField(max_length=250,unique=True)

    class Meta:
        ordering=('name',)
        
    def __str__(self):
        return self.name





class Gallery(models.Model):
    image=models.ImageField(upload_to='gallerys',blank=True)
    class Meta:
        ordering=('image',)
        
        
    def ImageField(self):
        return self.image




class Blog(models.Model):
    image=models.ImageField(upload_to='blog')
    name=models.CharField(max_length=250,unique=True)

    class Meta:
        ordering=('name',)
        
    def __str__(self):
        return self.name



class Package(models.Model):
    image=models.ImageField(upload_to='package')
    price=models.IntegerField()
    ln1=models.CharField(max_length=400)
    ln2=models.CharField(max_length=400)
    ln3=models.CharField(max_length=400)
    ln4=models.CharField(max_length=400)
    ln5=models.CharField(max_length=400)
    ln6=models.CharField(max_length=400)
    ln7=models.CharField(max_length=400,blank=True)
    ln8=models.CharField(max_length=400,blank=True)
    ln9=models.CharField(max_length=400,blank=True)
    ln10=models.CharField(max_length=400,blank=True)
    ln11=models.CharField(max_length=400,blank=True)
    ln12=models.CharField(max_length=400,blank=True)
    ln13=models.CharField(max_length=400,blank=True)
    name=models.CharField(max_length=250,unique=True)

    class Meta:
        ordering=('name',)
        
    def __str__(self):
        return self.name    



  

hospital_proj/hos_app/views.py
from django.shortcuts import render,HttpResponse,redirect
from .models import Homes,Branch,Gallery,Blog,Package,Enquery,Appointment,Contact,Testimo

# Create your views here.
def Home(request):
    homes=Homes.objects.all()
    testimo=Testimo.objects.all()
    if request.method=="POST": 
        names=request.POST.get('names','')
        email=request.POST.get('email','')
        number=request.POST.get('number','')
        message=request.POST.get('message','')       
        enq=Enquery(names=names,email=email,number=number,message=message)
        enq.save()
    return render(request,'index.html',{"homes":homes,"testimo":testimo})




def about(request):

    return render(request,'about.html')


def test(request):
    return render(request,'test.html')

def package(request):
    pack=Package.objects.all()
    return render(request,'package.html',{"pack":pack})



def packages(request,id):
    packs=Package.objects.get(id=id)
    return render(request,'packages.html',{'packs':packs})





def blog(request):
    blogs=Blog.objects.all()
    return render(request,'blog.html',{"blogs":blogs})


def blogpage(request):
    blog=Blog.objects.all()
    return render(request,'blogpage.html',{"blog":blog})


def blogpage1(request):
    blog1=Blog.objects.all()
    return render(request,'blogpage1.html',{"blog1":blog1})





def gallery(request):
    gallerys=Gallery.objects.all()
    return render(request,'gallery.html',{'gallerys':gallerys})



def branches(request):
    branch=Branch.objects.all()
    return render(request,'branches.html',{"branch":branch})



def branchplace(request,id):
    branchs=Branch.objects.get(id=id)
    return render(request,'branchplace.html',{'branchs':branchs})



def contacts(request):

    cont = Contact.objects.all()
    if request.method == "POST":
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        phone = request.POST.get('phone', '')
        subject = request.POST.get('subject','') 
        message = request.POST.get('message', '')


        if not phone:
            return HttpResponse("Phone number is required")  # Provide appropriate feedback to the user

        try:
            phone = int(phone)  # Convert phone to integer
        except ValueError:
            return HttpResponse("Invalid phone number")

        # Create and save the appointment
        enq = Contact(name=name, email=email, phone=phone, subject=subject, message=message)
        enq.save()
    return render(request,'contacts.html',{'cont':cont})




def appointment(request):
    hom = Appointment.objects.all()

    if request.method == "POST":
        name = request.POST.get('names', '')
        email = request.POST.get('email', '')
        phone = request.POST.get('phone', '')  # Ensure to provide a default value if the field is empty
        time = request.POST.get('time', '')
        date = request.POST.get('date', '')
        age = request.POST.get('age', '')
        gender = request.POST.get('gender', '')  # Corrected typo in 'state'
        address = request.POST.get('address', '')
        message = request.POST.get('message', '')

        # Validate phone number
        if not phone:
            return HttpResponse("Phone number is required")  # Provide appropriate feedback to the user

        try:
            phone = int(phone)  # Convert phone to integer
        except ValueError:
            return HttpResponse("Invalid phone number")

        # Create and save the appointment
        enq = Appointment(name=name, email=email, phone=phone, date=date, time=time, age=age, gender=gender, address=address, message=message)
        enq.save()

    return render(request, 'appointment.html', {"hom": hom})







def privacy(request):
    return render(request,'privacy.html')




def term(request):
    return render(request,'term.html')



def depart(request):
    return render(request,'depart.html')

hospital_proj/templates/blog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="packages w-100" id="package">
    <div class="row w-100">
        <div class="abi col-lg-6">

            <h1>Blog</h1>
            <h6>Unlocking genomics to reshape personalized healthcare,</h6>
            <h6>revolutionizing outcomes.</h6>

        </div>
        <div class="tip col-lg-6">
            <img src="../static/images/blog.jpg" alt="">
        </div>
    </div>
</section>


<section class="blog1">
    <div class="row blorw mx-auto d-flex">
        <div class="card ms-3" style="width: 24rem;">
            <a href="{% url 'hos:blogpage' %}">
            <img class="bloimg card-img-top" src="../static/images/bl01.jpg" alt="Card image cap"></a>
            <div class="ms-0 card-body brbo">
              <p class="card-text mt-2">Unlocking the Power of Genes: Exploring the Impact of Molecular Biology on Personalized Medicine</p>
            </div>
          </div>

          <div class="card ms-3" style="width: 24rem;">
            <a href="{% url 'hos:blogpage1' %}">
            <img class="bloimg card-img-top" src="../static/images/blo2.jpg" alt="Card image cap">
            <div class="lnkb">
                <img src="../static/images/link.svg" alt="">
            </div>
            </a>
            <div class="ms-0 card-body brbo">
              <p class="card-text mt-2">Beyond Images: The Vital Role of Radiology in Modern Diagnostic Excellence</p>
            </div>
          </div>

    </div>
</section>


<section class="footer">
    <div class="rw2 row mx-auto">
        <div class="col9 col-lg-8">
            <div class="row">
                <div class="col-lg-2">
                    <img class="mt-4 ms-3" src="../static/images/make-appointment.png" alt="">
                </div>
                <div class="col-lg-7 mt-4">
                    <h5 class="ms-3"> Make an Appointment</h5>
                    <h6 class="ms-3">Call +91 81388 62626 or click Book Now to secure your appointment.</h6>
                </div>
                <div class="col-lg-3">
                    <a href="{% url 'hos:appointment' %}">
                    <button type="button" class="btn4 mt-5 btn btn-dark ">Book Now</button>
                    </a>
                </div>
            </div>
        </div>

        <div class="col91 col-lg-4">
            <div class="row">
                <div class="col-lg-3">
                    <img class="mt-4" src="../static/images/openinh-hours-logo.png" alt="">
                </div>
                <div class="col-lg-9">
                    <h5 class="mt-3">Opening Hours</h5>
                    <h6>Mon - Sat : 6:30pm to 6:00pm</h6>
                    <h6>Sun : 6:30am - 12:30pm</h6>
                </div>
            </div>
        </div>
    </div>

    <div class="rw3 row">
        <div class="col-lg-2">
            <img src="../static/images/gmrl-footer-logo.svg" alt="">
        </div>
        <div class="col-lg-2">
            <h4 class="mb-4">Quick Links</h4>
            <h6>Home</h6>
            <h6>About Us</h6>
            <h6>Packages</h6>
            <h6>Tests</h6>
            <h6>Gallery</h6>
            <h6>Blog</h6>
            <h6>Testimonials</h6>
            <h6>Branches</h6>
            <h6>Contact Us</h6>
            <h6>Privacy Policy</h6>
            <h6>Terms & Conditions</h6>
        </div>

        <div class="col-lg-2">
            <h4 class="mb-4">Departments</h4>
            <h6>Pathology</h6>
            <h6>Biochemistry</h6>
            <h6>Microbiology</h6>
            <h6>Serology</h6>
            <h6>Immunology</h6>
            <h6>Radiology</h6>
            <h6>Molecular Biology</h6>
        </div>

        <div class="col-lg-3">
            <h4 class="mb-4">Our Packages</h4>
            <h6>Executive Package</h6>
            <h6>Ayush General</h6>
            <h6>Ayush Silver Plan</h6>
            <h6>Ayush Diabetic & Kidney Care</h6>
            <h6>Ayush Gold</h6>
            <h6>Advanced Cardiac Risk Cover Package</h6>

        </div>
        
        <div class="col-lg-3">
            <h4 class="mb-4">Get In Touch</h4>
            <h6>GMRL Laboratories Chambakkara, Ernakulam, Ernakulam - 682011</h6>
            <h6>+91 81388 62626</h6>
            <h6>0484 0000 0000</h6>
            <h6>info@gmrllabs.com</h6>
            <div class="rw4 row">
                <div class="col-lg-3">
                    <i class='bx bxl-facebook-circle' style='color:#0636a2'></i>
                </div>
                <div class="col-lg-3">
                    <i class='bx bxl-twitter' style='color:#00b2ef'></i>
                </div>
                <div class="col-lg-3">
                    <i class='bx bxl-linkedin'></i>
                </div>
                <div class="col-lg-3">
                    <i class='bx bxl-instagram' style='color:#ff7500'></i>
                </div>
            </div>
        </div>

    </div>
</section>






{% endblock %}

hospital_proj/templates/blogpage1.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="packages w-100" id="package">
    <div class="row w-100">
        <div class="abi col-lg-6">

            <h1>Blog</h1>
            <h6>Unlocking genomics to reshape personalized healthcare,</h6>
            <h6>revolutionizing outcomes.</h6>

        </div>
        <div class="tip col-lg-6">
            <img src="../static/images/blog.jpg" alt="">
        </div>
    </div>
</section>



<section class="blpage">
    <div class="row blpo d-flex mx-auto">
        <div class="col-lg-8">
            <h3>Beyond Images: The Vital Role of Radiology in Modern Diagnostic Excellence</h3>
            <h6 class="mt-3">06-Nov-2023</h6><hr>
            <h6 class="mt-4">In the realm of modern healthcare, the field of radiology stands as a cornerstone for accurate and comprehensive diagnostics. Radiological imaging goes beyond mere visuals, playing a vital role in enhancing diagnostic excellence and influencing the course of patient care.</h6>
            
            <h3 class="mt-4">The Evolution of Radiology: From Film to Digital Precision</h3>
            <h6>Molecular biology enables us to decipher the intricate genetic code that defines each person. Through techniques like DNA sequencing, researchers can identify variations and mutations within the genome, providing crucial insights into an individual’s susceptibility to certain diseases, response to medications, and overall health profile. This personalized blueprint forms the foundation for more targeted and effective medical interventions.</h6>
            
            <h3 class="mt-4">Tailoring Treatments: Precision Medicine in Action</h3>
            <h6>The era of one-size-fits-all medicine is gradually giving way to precision medicine, thanks to the contributions of molecular biology. Understanding the specific genetic markers associated with a disease allows healthcare providers to prescribe treatments that are precisely matched to the patient’s genetic profile. This targeted approach minimizes adverse reactions, enhances treatment efficacy, and improves overall patient outcomes.</h6>
            
            <h3 class="mt-4">Predictive Medicine: Anticipating and Preventing Diseases</h3>
            <h6>Molecular biology not only aids in the treatment of existing conditions but also plays a crucial role in predicting and preventing diseases. Genetic testing can identify individuals with a higher risk of developing certain conditions, empowering both patients and healthcare providers to proactively address potential health threats. Early interventions and lifestyle modifications based on genetic insights contribute to a more proactive and preventive approach to healthcare.</h6>
            
            <h3 class="mt-4">Pharmacogenomics: Optimizing Medication Responses</h3>
            <h6>One of the groundbreaking applications of molecular biology is found in pharmacogenomics—the study of how an individual’s genetic makeup influences their response to medications. By analyzing genetic variations, healthcare providers can prescribe medications that are more likely to be effective and less likely to cause adverse reactions. This approach not only enhances treatment outcomes but also minimizes the trial-and-error process often associated with medication selection.</h6>
            
            <h3 class="mt-4">Ethical Considerations: Navigating the Genetic Landscape</h3>
            <h6>As the field of molecular biology advances, ethical considerations become paramount. Issues such as privacy, consent, and the responsible use of genetic information require careful navigation. Striking a balance between harnessing the power of genetics for personalized medicine and safeguarding individual rights is essential for the continued progress and acceptance of these transformative technologies.</h6>
            
            <h3 class="mt-4">The Future of Healthcare: A Genomic Revolution</h3>
            <h6>The impact of molecular biology on personalized medicine is profound, ushering in a new era in healthcare. As technology continues to advance, and our understanding of the genome deepens, the potential for more precise, individualized, and effective medical interventions becomes limitless. The ongoing genomic revolution holds the promise of reshaping the healthcare landscape, offering new hope for improved patient outcomes and a healthier, more personalized approach to medicine.</h6>
        </div>
        
        <div class="col-lg-4">
            <img src="../static/images/blo2.jpg" alt="">
            <h3 class="mt-5">Recent Posts</h3>
            <h6 class="blom mt-3" ><img src="../static/images/done_FILL0_wght400_GRAD0_opsz24.svg" alt=""> <a class="colblo" href="{% url 'hos:blogpage' %}"> Unlocking the Power of Genes: Exploring the Impact of Molecular Biology on Personalized Medicine</h6></da>
            <h6 class="blom" ><img src="../static/images/done_FILL0_wght400_GRAD0_opsz24.svg" alt=""> <a class="colblo" href="{% url 'hos:blogpage1' %}"> Beyond Images: The Vital Role of Radiology in Modern Diagnostic Excellence</h6></a>
        </div>
    </div>
</section>

<section class="footer">
    <div class="rw2 row mx-auto">
        <div class="col9 col-lg-8">
            <div class="row">
                <div class="col-lg-2">
                    <img class="mt-4 ms-3" src="../static/images/make-appointment.png" alt="">
                </div>
                <div class="col-lg-7 mt-4">
                    <h5 class="ms-3"> Make an Appointment</h5>
                    <h6 class="ms-3">Call +91 81388 62626 or click Book Now to secure your appointment.</h6>
                </div>
                <div class="col-lg-3">
                    <a href="{% url 'hos:appointment' %}">
                    <button type="button" class="btn4 mt-5 btn btn-dark ">Book Now</button>
                    </a>
                </div>
            </div>
        </div>

        <div class="col91 col-lg-4">
            <div class="row">
                <div class="col-lg-3">
                    <img class="mt-4" src="../static/images/openinh-hours-logo.png" alt="">
                </div>
                <div class="col-lg-9">
                    <h5 class="mt-3">Opening Hours</h5>
                    <h6>Mon - Sat : 6:30pm to 6:00pm</h6>
                    <h6>Sun : 6:30am - 12:30pm</h6>
                </div>
            </div>
        </div>
    </div>

    <div class="rw3 row">
        <div class="col-lg-2">
            <img src="../static/images/gmrl-footer-logo.svg" alt="">
        </div>

        <div class="col-lg-2">
            <h4 class="mb-4">Quick Links</h4>
            <h6>Home</h6>
            <h6>About Us</h6>
            <h6>Packages</h6>
            <h6>Tests</h6>
            <h6>Gallery</h6>
            <h6>Blog</h6>
            <h6>Testimonials</h6>
            <h6>Branches</h6>
            <h6>Contact Us</h6>
            <h6>Privacy Policy</h6>
            <h6>Terms & Conditions</h6>
        </div>

        <div class="col-lg-2">
            <h4 class="mb-4">Departments</h4>
            <h6>Pathology</h6>
            <h6>Biochemistry</h6>
            <h6>Microbiology</h6>
            <h6>Serology</h6>
            <h6>Immunology</h6>
            <h6>Radiology</h6>
            <h6>Molecular Biology</h6>
        </div>

        <div class="col-lg-3">
            <h4 class="mb-4">Our Packages</h4>
            <h6>Executive Package</h6>
            <h6>Ayush General</h6>
            <h6>Ayush Silver Plan</h6>
            <h6>Ayush Diabetic & Kidney Care</h6>
            <h6>Ayush Gold</h6>
            <h6>Advanced Cardiac Risk Cover Package</h6>

        </div>

        <div class="col-lg-3">
            <h4 class="mb-4">Get In Touch</h4>
            <h6>GMRL Laboratories Chambakkara, Ernakulam, Ernakulam - 682011</h6>
            <h6>+91 81388 62626</h6>
            <h6>0484 0000 0000</h6>
            <h6>info@gmrllabs.com</h6>
            <div class="rw4 row">
                <div class="col-lg-3">
                    <i class='bx bxl-facebook-circle' style='color:#0636a2'></i>
                </div>
                <div class="col-lg-3">
                    <i class='bx bxl-twitter' style='color:#00b2ef'></i>
                </div>
                <div class="col-lg-3">
                    <i class='bx bxl-linkedin'></i>
                </div>
                <div class="col-lg-3">
                    <i class='bx bxl-instagram' style='color:#ff7500'></i>
                </div>
            </div>
        </div>

    </div>
</section>

{% endblock %}

hospital_proj/templates/gallery.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="packages w-100" id="package">
    <div class="row w-100">
        <div class="abi col-lg-6">

            <h1>Gallery</h1>
            <h6>Step into the visual journey of GMRL Labs in Tripunithura—a gallery</h6>
            <h6>showcasing our commitment to health and excellence.</h6>

        </div>
        
        <div class="tip col-lg-6">
            <img src="../static/images/gallary.jpg" alt="">
        </div>
    </div>
</section>



<section class="gall">
    <div class="row galrw mx-auto d-flex">
        {% for k in gallerys %}
        <div class="contan">
        <img class="ms-0 me-3 mt-3 pe-0 ps-0" src="{{k.image.url}}" alt="">
        <div class="seri">
            <i class='bx bx-search' style='color:#ffffff'  ></i>
        </div>
        </div>
        {% endfor %}
    </div>
</section>


<section class="footer">
    <div class="rw2 row mx-auto">
        <div class="col9 col-lg-8">
            <div class="row">
                <div class="col-lg-2">
                    <img class="mt-4 ms-3" src="../static/images/make-appointment.png" alt="">
                </div>
                <div class="col-lg-7 mt-4">
                    <h5 class="ms-3"> Make an Appointment</h5>
                    <h6 class="ms-3">Call +91 81388 62626 or click Book Now to secure your appointment.</h6>
                </div>
                <div class="col-lg-3">
                    <a href="{% url 'hos:appointment' %}">
                    <button type="button" class="btn4 mt-5 btn btn-dark ">Book Now</button>
                    </a>
                </div>
            </div>
        </div>

        <div class="col91 col-lg-4">
            <div class="row">
                <div class="col-lg-3">
                    <img class="mt-4" src="../static/images/openinh-hours-logo.png" alt="">
                </div>
                <div class="col-lg-9">
                    <h5 class="mt-3">Opening Hours</h5>
                    <h6>Mon - Sat : 6:30pm to 6:00pm</h6>
                    <h6>Sun : 6:30am - 12:30pm</h6>
                </div>
            </div>
        </div>
    </div>

    <div class="rw3 row">
        <div class="col-lg-2">
            <img src="../static/images/gmrl-footer-logo.svg" alt="">
        </div>

        <div class="col-lg-2">
            <h4 class="mb-4">Quick Links</h4>
            <h6>Home</h6>
            <h6>About Us</h6>
            <h6>Packages</h6>
            <h6>Tests</h6>
            <h6>Gallery</h6>
            <h6>Blog</h6>
            <h6>Testimonials</h6>
            <h6>Branches</h6>
            <h6>Contact Us</h6>
            <h6>Privacy Policy</h6>
            <h6>Terms & Conditions</h6>
        </div>

        <div class="col-lg-2">
            <h4 class="mb-4">Departments</h4>
            <h6>Pathology</h6>
            <h6>Biochemistry</h6>
            <h6>Microbiology</h6>
            <h6>Serology</h6>
            <h6>Immunology</h6>
            <h6>Radiology</h6>
            <h6>Molecular Biology</h6>
        </div>

        <div class="col-lg-3">
            <h4 class="mb-4">Our Packages</h4>
            <h6>Executive Package</h6>
            <h6>Ayush General</h6>
            <h6>Ayush Silver Plan</h6>
            <h6>Ayush Diabetic & Kidney Care</h6>
            <h6>Ayush Gold</h6>
            <h6>Advanced Cardiac Risk Cover Package</h6>

        </div>

        <div class="col-lg-3">
            <h4 class="mb-4">Get In Touch</h4>
            <h6>GMRL Laboratories Chambakkara, Ernakulam, Ernakulam - 682011</h6>
            <h6>+91 81388 62626</h6>
            <h6>0484 0000 0000</h6>
            <h6>info@gmrllabs.com</h6>
            <div class="rw4 row">
                <div class="col-lg-3">
                    <i class='bx bxl-facebook-circle' style='color:#0636a2'></i>
                </div>
                <div class="col-lg-3">
                    <i class='bx bxl-twitter' style='color:#00b2ef'></i>
                </div>
                <div class="col-lg-3">
                    <i class='bx bxl-linkedin'></i>
                </div>
                <div class="col-lg-3">
                    <i class='bx bxl-instagram' style='color:#ff7500'></i>
                </div>
            </div>
        </div>

    </div>
</section>

{% endblock %}

hospital_proj/templates/nav.html
{% load static %}
<div class="mqin">
    <div class="rw1 row">
        <div class="col-lg-6 col-md-6 col-sm-6 oci">
            <ul class="socialmedia d-flex justify-content-end">
                <a href="" class="fb me-4" target="_blank">
                    <i class='bx bxl-facebook-circle' style='color:#525252'></i>
                </a>

                <a href="" class="tw me-4" target="_blank">
                    <i class='bx bxl-twitter' style='color:#7b7b7b'></i>
                </a>
                <a href="" class="li me-4" target="_blank">
                    <i class='bx bxl-linkedin' style='color:#7b7b7b'></i>
                </a>
                <a href="" class="in" target="_blank">
                    <i class='bx bxl-instagram' style='color:#7b7b7b'></i>
                </a>
            </ul>

        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 maker">
            <a href="{% url 'hos:appointment' %}"><button class="btn btn">Make An Appointment</button></a>
        </div>
    </div>
    <nav id="navbar" class="navbar shadow-lg navbar-expand-lg bg-light mx-auto">
      <div class="container-fluid">
        <a href="{% url 'hos:home' %}"><img class="ima" style="margin-left: 60px;" src="../static/images/gmrl-logo.svg" width="280px" alt=""></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse  navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="btn nav-link" href="{% url 'hos:about' %}">ABOUT</a>
                </li>
                <li class="nav-item">
                    <a class="btn nav-link" href="{% url 'hos:test' %}">TESTS</a>
                </li>

                <li class="nav-item">
                    <a class="btn nav-link" href="{% url 'hos:package' %}">PACKAGES</a>
                </li>
                <li class="nav-item">
                    <a class="btn nav-link" href="{% url 'hos:blog' %}">BLOG</a>
                </li>
                <li class="nav-item">
                    <a class="btn nav-link" href="{% url 'hos:gallery' %}">GALLERY</a>
                </li>
                <li class="nav-item">
                    <a class="btn nav-link" href="{% url 'hos:branches' %}">BRANCHES</a>
                </li>
                <li class="nav-item">
                    <a class="btn nav-link" href="{% url 'hos:contacts' %}">CONTACT US</a>
                </li>
            </ul>
        </div>
      </div>
    </nav>
  </div>


  <script>
    window.addEventListener('scroll', function() {
      var navbar = document.getElementById('navbar');
      if (window.scrollY > 100) 
      {
        navbar.classList.add('sticky-navbar');
        navbar.style.width='100vw';

      } 
        else {
        navbar.classList.remove('sticky-navbar');
        navbar.style.width='88vw';

        
      }
    });


    
  </script>
<section class="header-fixed fixed-top headertop-div">

</section>